### ISSUE TITLE
[bug]: error code: 524 on line 1548 of file /var/www/html/admin/modules/soundlang/Soundlang.class.php

### ISSUE THREAD

**Issue by Af0x** [FreePBX/soundlang#5]
### FreePBX Version

FreePBX 17

### Issue Description

While restoring from a FreePBX 16 backup, there is the attached error

### Operating Environment

Fresh Debian 12, FreePBX installation with Beta skript

### Relevant log output

```shell
Processing soundlang
Resetting soundlang module data
Dropping table soundlang_packages...Done
Dropping table soundlang_settings...Done
Dropping table soundlang_customlangs...Done
Dropping table soundlang_prompts...Done
Updating tables soundlang_packages, soundlang_settings, soundlang_customlangs, soundlang_prompts...Done
New install, downloading default english language set...
Installing core-sounds-g722...Done
Installing core-sounds-ulaw...Done
Installing extra-sounds-g722...Done
Installing extra-sounds-ulaw...Done
Finished installing default sounds
Installing additional package core-sounds-alaw...Done
Installing additional package core-sounds-alaw...error code: 524 on line 1548 of file /var/www/html/admin/modules/soundlang/Soundlang.class.php
#0 /var/www/html/admin/modules/soundlang/Soundlang.class.php(1344): FreePBX\modules\Soundlang->getRemoteFile()
FreePBX/sng_freepbx_debian_install#1 /var/www/html/admin/modules/soundlang/install.php(76): FreePBX\modules\Soundlang->installPackage()
FreePBX/sng_freepbx_debian_install#2 /var/www/html/admin/libraries/modulefunctions.class.php(2684): include_once('...')
FreePBX/sng_freepbx_debian_install#3 /var/www/html/admin/libraries/modulefunctions.class.php(2600): module_functions->_doinclude()
FreePBX/sng_freepbx_debian_install#4 /var/www/html/admin/libraries/modulefunctions.class.php(2066): module_functions->_runscripts()
FreePBX/sng_freepbx_debian_install#5 /var/www/html/admin/modules/backup/Handlers/FreePBXModule.php(28): module_functions->install()
FreePBX/sng_freepbx_debian_install#6 /var/www/html/admin/modules/backup/Handlers/FreePBXModule.php(23): FreePBX\modules\Backup\Handlers\FreePBXModule->install()
FreePBX/sng_freepbx_debian_install#7 /var/www/html/admin/modules/backup/Models/Restore.php(58): FreePBX\modules\Backup\Handlers\FreePBXModule->reset()
FreePBX/soundlang#5 /var/www/html/admin/modules/backup/Handlers/Restore/Common.php(121): FreePBX\modules\Backup\Models\Restore->reset()
FreePBX/sng_freepbx_debian_install#9 /var/www/html/admin/modules/backup/Handlers/Restore/Multiple.php(70): FreePBX\modules\Backup\Handlers\Restore\Common->processModule()
FreePBX/framework#112 /var/www/html/admin/modules/backup/Console/Backup.class.php(340): FreePBX\modules\Backup\Handlers\Restore\Multiple->process()
FreePBX/setcid#5 /var/www/html/admin/libraries/Composer/vendor/symfony/console/Command/Command.php(312): FreePBX\Console\Command\Backup->execute()
FreePBX/sng_freepbx_debian_install#12 /var/www/html/admin/libraries/Composer/vendor/symfony/console/Application.php(1022): Symfony\Component\Console\Command\Command->run()
FreePBX/sng_freepbx_debian_install#13 /var/www/html/admin/libraries/Composer/vendor/symfony/console/Application.php(314): Symfony\Component\Console\Application->doRunCommand()
FreePBX/sng_freepbx_debian_install#14 /var/www/html/admin/libraries/Composer/vendor/symfony/console/Application.php(168): Symfony\Component\Console\Application->doRun()
#15 /var/lib/asterisk/bin/fwconsole(163): Symfony\Component\Console\Application->run()
#16 {main}
Processing recordings
Resetting recordings module data
Dropping table recordings...Done
Updating tables recordings...Done
Generating CSS...Done
Restoring from recordings [FreePBX\modules\Recordings\Restore]
Done
```

**Comment by kapilgupta01** [comment]
Hi @Af0x are you still facing this issue on latest modules? thanks

**Comment by kapilgupta01** [comment]
Please try with the latest soundlang module. thanks
